development:
  adapter: postgresql
  encoding: utf8
  database: simple_blog
  pool: 5
  username: sbastidasr
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: simple_blog_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: simple_blog_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
